### ISSUE TITLE
Update ReadMe informations

### ISSUE THREAD

**Issue by fatemi2020** [ZarinPal-Lab/Android-SDK#4]
Hi,
I try using this library but as the version of library in read me or even in release page was incorrect, I could not build the project.
So I search the web by package name and found this page:
[https://search.maven.org/artifact/com.zarinpal/payment-provider](https://search.maven.org/artifact/com.zarinpal/payment-provider)

Please update the Read me information after make new releases!!!

**Comment by ImanX** [comment]
Thank for reporting issue
The Repo'll archive please follow new [Repo](https://github.com/ZarinPal/Android-SDK)
