### ISSUE TITLE
Wrong checking valid Uri

### ISSUE THREAD

**Issue by fatemi2020** [ZarinPal-Lab/Android-SDK#5]
Hi,
In the `DirectlyPurchase` class, this line:
`require(!callbackURL.isValidURI()) { "The URI is Invalid" }`
must be:
`require(callbackURL.isValidURI()) { "The URI is Invalid" }`

you must remove `!` mark

**Comment by ImanX** [comment]
Thank for reporting issue
The Repo'll archive please follow new [Repo](https://github.com/ZarinPal/Android-SDK)
